name: lrc_neural
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _tflow_select=2.1.0
  - abseil-cpp=20230802.0
  - absl-py=2.1.0
  - aiohttp=3.9.5
  - aiosignal=1.2.0
  - astor=0.8.1
  - astunparse=1.6.3
  - async-timeout=4.0.3
  - attrs=23.1.0
  - blas=1.0
  - blinker=1.6.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.7.2
  - cachetools=5.3.3
  - certifi=2024.7.4
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - click=8.1.7
  - cryptography=42.0.5
  - cudatoolkit=10.1.243
  - cudnn=7.6.5
  - cupti=10.1.168
  - freetype=2.12.1
  - frozenlist=1.4.0
  - gast=0.4.0
  - google-auth=2.29.0
  - google-auth-oauthlib=0.5.2
  - google-pasta=0.2.0
  - grpc-cpp=1.48.2
  - grpcio=1.48.2
  - gtest=1.14.0
  - h5py=2.10.0
  - hdf5=1.10.6
  - idna=3.7
  - importlib-metadata=7.0.1
  - importlib_resources=6.4.0
  - intel-openmp=2023.1.0
  - jpeg=9e
  - keras=2.4.3
  - keras-base=2.4.3
  - keras-preprocessing=1.1.2
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - markdown=3.4.1
  - markupsafe=2.1.3
  - matplotlib-base=3.5.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - multidict=6.0.4
  - ncurses=6.4
  - numpy=1.19.5
  - numpy-base=1.19.5
  - oauthlib=3.2.2
  - openjpeg=2.4.0
  - openssl=3.0.14
  - opt_einsum=3.3.0
  - packaging=24.1
  - pandas=1.2.4
  - pillow=10.4.0
  - pip=24.0
  - platformdirs=3.10.0
  - pooch=1.7.0
  - protobuf=3.20.3
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pybind11-abi=4
  - pycparser=2.21
  - pyjwt=2.8.0
  - pyopenssl=24.0.0
  - pysocks=1.7.1
  - python=3.9.19
  - python-dateutil=2.9.0post0
  - python-flatbuffers=2.0
  - python-tzdata=2023.3
  - pytz=2024.1
  - pyyaml=6.0.1
  - re2=2022.04.01
  - readline=8.2
  - requests=2.32.2
  - requests-oauthlib=2.0.0
  - rsa=4.7.2
  - scipy=1.10.1
  - seaborn=0.12.2
  - setuptools=69.5.1
  - six=1.16.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tensorboard=2.12.1
  - tensorboard-data-server=0.7.0
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.4.1
  - tensorflow-base=2.4.1
  - tensorflow-estimator=2.6.0
  - tensorflow-gpu=2.4.1
  - termcolor=2.1.0
  - tk=8.6.14
  - tzdata=2024a
  - unicodedata2=15.1.0
  - urllib3=2.2.2
  - werkzeug=3.0.3
  - wheel=0.43.0
  - wrapt=1.14.1
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.9.3
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - contourpy==1.2.1
      - cycler==0.12.1
      - fonttools==4.53.1
      - imageio==2.37.0
      - kiwisolver==1.4.5
      - matplotlib==3.9.1
      - pyparsing==3.1.2
      - tfdiffeq==0.0.1
      - tqdm==4.67.1